tecnicas_de_estudio=(
    ('Pomodoro', 'Pomodoro'),
    ('Mapas mentales', 'Mapas mentales'),
    ('Resúmenes', 'Resúmenes'),
    ('Listas', 'Listas'),
    ('Cuadro comparativo', 'Cuadro comparativo'),
    ('Realizar ejercicios', 'Realizar ejercicios'),
    ('Explicar el tema', 'Explicar el tema'),
    ('Leer en voz alta', 'Leer en voz alta'),
    ('Encontrar exámenes pasados', 'Encontrar exámenes pasados'),
    ('Autoevaluación', 'Autoevaluación'),
    ('Calendario de estudios', 'Calendario de estudios'),
    ('Organización del tiempo', 'Organización del tiempo'),
    ('Grupos de estudios', 'Grupos de estudios'),
    ('Flash cards, fichas de estudio o tarjetas de estudio', 'Flash cards, fichas de estudio o tarjetas de estudio'),
    ('Apuntes clásicos', 'Apuntes clásicos'),
    ('Subrayar lo importante', 'Subrayar lo importante'),
    ('Mnemotecnia', 'Mnemotecnia'),
    ('Método de Cornell', 'Método de Cornell'),
    ('Podcast', 'Podcast'),
    ('Brainstorming', 'Brainstorming'),
    ('Métodos basados en imágenes', 'Métodos basados en imágenes'),
    ('Crea foros online para preparar el examen', 'Crea foros online para preparar el examen'),
    ('Realizar tus propios apuntes', 'Realizar tus propios apuntes'),
    ('Fichas de estudio', 'Fichas de estudio'),
    ('Desarrollar un calendario y tomar en cuenta tus objetivos y el tiempo que tienes disponible',
    'Desarrollar un calendario y tomar en cuenta tus objetivos y el tiempo que tienes disponible'),
    ('Elaborar preguntas','Elaborar preguntas'),
)