# Generated by Django 4.2.1 on 2023-06-01 19:20

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('token', models.UUIDField(blank=True, editable=False, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Indicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación')),
                ('users', models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Indicación',
                'verbose_name_plural': 'Indicaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Dni')),
                ('birthday', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Masculino', max_length=10, verbose_name='Genero')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('tecnica_estudio', models.CharField(max_length=50, null=True, verbose_name='Técnica de estudio')),
                ('etnia', models.CharField(choices=[('Afroecuatoriano', 'Afroecuatoriano'), ('Blanco', 'Blanco'), ('Cholo', 'Cholo'), ('Indigena', 'Indigena'), ('Montubio', 'Montubio'), ('Mulato', 'Mulato'), ('Mestizo', 'Mestizo'), ('Negro', 'Negro'), ('Otro', 'Otro')], max_length=100, verbose_name='Etnia')),
                ('nacionalidad', models.CharField(choices=[('Afgana', 'Afganistán'), ('Albanés', 'Albania'), ('Alemana', 'Alemania'), ('Andorrana', 'Andorra'), ('Angoleña', 'Angola'), ('Antiguana', 'Antigua y Barbuda'), ('Árabe', 'Arabia Saudita / Arabia Saudí'), ('Argelina', 'Argelia'), ('Argentina', 'Argentina'), ('Armenia', 'Armenia'), ('Australiana ', 'Australia'), ('Austriaca', 'Austria'), ('Azerbaiyano', 'Azerbaiyán'), ('Bahamas', 'Bahamas'), ('Bangladesí', 'Bangladés'), ('Barbadense', 'Barbados'), ('Bareiní', 'Baréin'), ('Belga', 'Bélgica'), ('Beliceña', 'Belice'), ('Bielorusa', 'Bielorrusia'), ('Beninesa', 'Benín'), ('Birmana', 'Birmania'), ('Boliviana ', 'Bolivia'), ('Bosnia', 'Bosnia y Herzegovina'), ('Botsuana', 'Botsuana'), ('Brasileña', 'Brasil'), ('Bruneana', 'Brunei'), ('Búlgara', 'Bulgaria'), ('Burkinés', 'Burkina Faso'), ('Burundesa', 'Burundi'), ('Butanés', 'Bután'), ('Caboverdiano', 'Cabo Verde'), ('Camboyana', 'Camboya'), ('Camerunesa', 'Camerún'), ('Canadiense', 'Canadá'), ('Centroafricana', 'República Centroafricana'), ('Chadiana', 'Chad'), ('Checa', 'República Checa / Chequia'), ('Chilena', 'Chile'), ('China', 'China'), ('Chipriota', 'Chipre'), ('Colombiana ', 'Colombia'), ('Comoras', 'Comoras'), ('Congoleña', 'República del Congo'), ('Congoleña,', 'República Democrática del Congo'), ('Coreana', 'Corea del Norte'), ('Coreana', 'Corea del Sur'), ('Costarricense', 'Costa de Marfil'), ('Costarricense', 'Costa Rica'), ('Croata', 'Croacia'), ('Cubana', 'Cuba'), ('Danesa', 'Dinamarca'), ('Dominiquesa', 'Dominica'), ('Dominicana', 'República Dominicana'), ('Ecuatoriana', 'Ecuador'), ('Egipcia', 'Egipto'), ('Salvadoreña', 'El Salvador'), ('Emiratí', 'Emiratos Árabes Unidos'), ('Eritrea', 'Eritrea'), ('Eslovaca', 'Eslovaquia'), ('Eslovena ', 'Eslovenia'), ('Española', 'España'), ('Estadounidense', 'Estados Unidos'), ('Estona', 'Estonia'), ('Etiope', 'Etiopía'), ('Filipina', 'Filipinas'), ('Finlandesa', 'Finlandia'), ('Fiyiana', 'Fiyi'), ('Francesa', 'Francia'), ('Gabonesa', 'Gabón'), ('Gambiana', 'Gambia'), ('Georgiana', 'Georgia'), ('Ghanesa', 'Ghana'), ('Granadina', 'Granada'), ('Griega', 'Grecia'), ('Guatemalteca', 'Guatemala'), ('Guineana', 'Guinea'), ('Bisauguineana', 'Guinea-Bisáu'), ('Ecuatoguineana', 'Guinea Ecuatorial'), ('Guyanesa', 'Guyana'), ('Haitiana ', 'Haití'), ('Hondureña', 'Honduras'), ('Húngara', 'Hungría'), ('Indonesa ', 'India'), ('Indonesa', 'Indonesia'), ('Iraquí ', 'Irak'), ('Iraní', 'Irán'), ('Irlandesa', 'Irlanda'), ('Islandesa', 'Islandia'), ('Israelí', 'Israel'), ('Italiana', 'Italia'), ('Jamaicana', 'Jamaica'), ('Japonesa ', 'Japón'), ('Jordana', 'Jordania'), ('Kazaj0', 'Kazajistán'), ('Keniana', 'Kenia'), ('Kirguisa', 'Kirguistán'), ('Kiribatiana', 'Kiribati'), ('Kuwaití', 'Kuwait'), ('Laosiana', 'Laos'), ('Lesotense', 'Lesoto'), ('Letona', 'Letonia'), ('Libanesa', 'Líbano'), ('Liberiana', 'Liberia'), ('Libia', 'Libia'), ('Liechtensteiniano', 'Liechtenstein'), ('Lituana', 'Lituania'), ('Luxemburguesa', 'Luxemburgo'), ('Macedonia', 'Macedonia del Norte'), ('Malgache', 'Madagascar'), ('Malaya ', 'Malasia'), ('Malauí', 'Malaui'), ('Maldiva', 'Maldivas'), ('Malies', 'Mali / Malí'), ('maltesa', 'Malta'), ('Marroquí', 'Marruecos'), ('Marshalesa', 'Islas Marshall'), ('Mauriciana', 'Mauricio'), ('Mauritana', 'Mauritania'), ('Mexicana', 'México'), ('Micronesio', 'Micronesia'), ('Moldava', 'Moldavia'), ('Monegasca', 'Mónaco'), ('Mongola', 'Mongolia'), ('Montenegrina', 'Montenegro'), ('Mozambiqueña', 'Mozambique'), ('Namibia', 'Namibia'), ('Nauruano', 'Nauru'), ('Nepalí', 'Nepal'), ('Nicaragüense ', 'Nicaragua'), ('Nigerina', 'Níger'), ('Nigeriana', 'Nigeria'), ('Noruega', 'Noruega'), ('Neozelandesa', 'Nueva Zelanda / Nueva Zelandia'), ('Omaní', 'Omán'), ('Holandesa', 'Países Bajos'), ('Pakistaní', 'Pakistán'), ('Palauana', 'Palaos'), ('Palestina', 'Palestina'), ('Panameña', 'Panamá'), ('Papuanos', 'Papúa Nueva Guinea'), ('Paraguaya', 'Paraguay'), ('Peruana', 'Perú'), ('Polaca', 'Polonia'), ('Portuguesa \t', 'Portugal'), ('Qatarí', 'Qatar'), ('Británica', 'Reino Unido'), ('Ruandesa', 'Ruanda'), ('Rumana', 'Rumania / Rumanía'), ('Rusa', 'Rusia'), ('Salomonense', 'Islas Salomón'), ('Samoana', 'Samoa'), ('Sancristobaleña', 'San Cristóbal y Nieves'), ('Sanmarinense', 'San Marino'), ('Sanvicentina', 'San Vicente y las Granadinas'), ('Santalucense', 'Santa Lucía'), ('Santotomense', 'Santo Tomé y Príncipe'), ('Senegalesa', 'Senegal'), ('Serbia', 'Serbia'), ('Seychelense', 'Seychelles'), ('Sierraleonés', 'Sierra Leona'), ('Singapurense', 'Singapur'), ('Siria', 'Siria'), ('Somalia', 'Somalia'), ('Esrilanqués', 'Sri Lanka'), ('Suazi', 'Suazilandia / Esuatini'), ('Sudafricana', 'Sudáfrica'), ('Sudanesa', 'Sudán'), ('Sursudanesa', 'Sudán del Sur'), ('Sueca', 'Suecia'), ('Suiza', 'Suiza'), ('Surinamesa', 'Surinam'), ('Tailandesa', 'Tailandia'), ('Tanzana', 'Tanzania'), ('Tayika', 'Tayikistán'), ('Timorense', 'Timor Oriental'), ('Togolesa', 'Togo'), ('Tongana', 'Tonga'), ('Trinitense', 'Trinidad y Tobago'), ('Tunecina', 'Túnez'), ('Turcomana', 'Turkmenistán'), ('Turca', 'Turquía'), ('Tuvaluana', 'Tuvalu'), ('Ucraniana', 'Ucrania'), ('Ugandesa', 'Uganda'), ('Uruguaya', 'Uruguay'), ('Uzbeka', 'Uzbekistán'), ('Vanuatuense', 'Vanuatu'), ('Vaticana', 'Ciudad del Vaticano'), ('Venezolana', 'Venezuela'), ('Vietnamita', 'Vietnam'), ('Yemenita', 'Yemen'), ('Yibutiana', 'Yibuti'), ('Zambiana', 'Zambia'), ('Zimbabuense', 'Zimbabue'), ('Otro', 'Otro')], max_length=100, verbose_name='Nacionalidad')),
                ('estado_civil', models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=100, verbose_name='Estado civil')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='userF', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
                'ordering': ['id'],
            },
        ),
    ]
