# Generated by Django 4.1.4 on 2023-01-31 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_remove_carrera_curso_carrera_curso'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carrera',
        ),
        migrations.AddField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrera', to='srea.curso', verbose_name='Carrera'),
        ),
    ]
