# Generated by Django 4.1.4 on 2023-01-10 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficha',
            name='email',
        ),
    ]
