# Generated by Django 4.1.4 on 2023-04-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nacionalidad',
            field=models.CharField(choices=[('ecuatoriana', 'Ecuador'), ('peruana', 'Perú'), ('colombiana', 'Colombia'), ('Otro', 'Otro')], default=2, max_length=100, verbose_name='Nacionalidad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ficha',
            name='etnia',
            field=models.CharField(choices=[('Afroecuatoriano', 'Afroecuatoriano'), ('Blanco', 'Blanco'), ('Cholo', 'Cholo'), ('Indigena', 'Indigena'), ('Montubio', 'Montubio'), ('Mulato', 'Mulato'), ('Mestizo', 'Mestizo'), ('Negro', 'Negro'), ('Otro', 'Otro')], max_length=100, verbose_name='Etnia'),
        ),
    ]
