# Generated by Django 4.1.4 on 2023-01-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_ficha_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='codigo',
        ),
    ]
