# Generated by Django 4.1.4 on 2023-01-31 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_carrera_user_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
    ]
