# Generated by Django 4.2.1 on 2023-06-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_indicacion_slug_remove_indicacion_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicacion',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='indicacion',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción'),
        ),
    ]
