# Generated by Django 4.1.4 on 2023-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ficha_nacionalidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a')], max_length=100, verbose_name='Estado civil'),
        ),
    ]
