# Generated by Django 4.1.4 on 2023-01-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_carrera_codigo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'ordering': ['id'], 'verbose_name': 'Ficha', 'verbose_name_plural': 'Fichas'},
        ),
    ]
