# Generated by Django 4.1.4 on 2023-01-24 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_ficha_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ficha',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='user.ficha', verbose_name='Ficha'),
            preserve_default=False,
        ),
    ]
