# Generated by Django 4.2.1 on 2023-06-19 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_indicacion_user_indicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicacion',
            old_name='user',
            new_name='autor',
        ),
    ]
