# Generated by Django 4.1.4 on 2023-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0008_alter_carrera_curso'),
        ('user', '0004_user_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='curso', to='srea.curso', verbose_name='Ciclos'),
        ),
    ]
