# Generated by Django 4.1.4 on 2023-01-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ficha',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='user.ficha', verbose_name='Ficha'),
        ),
    ]
