# Generated by Django 4.1.4 on 2023-01-24 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='carrera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carrera', to='user.carrera', verbose_name='Carrera'),
        ),
    ]
