# Generated by Django 4.1.4 on 2023-02-01 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0008_alter_carrera_curso'),
        ('user', '0006_remove_user_curso_user_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='srea.curso', verbose_name='Ciclo'),
            preserve_default=False,
        ),
    ]
