# Generated by Django 4.2.1 on 2023-06-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_indicacion_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacion',
            name='user_indicacion',
        ),
    ]
