# Generated by Django 4.2.1 on 2023-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_indicacion_autor_indicacion_user_indicacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicacion',
            options={'ordering': ['id'], 'verbose_name': 'Inidicación', 'verbose_name_plural': 'Indicaciones'},
        ),
        migrations.RemoveField(
            model_name='indicacion',
            name='slug',
        ),
    ]
