# Generated by Django 4.1.4 on 2023-02-01 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0008_alter_carrera_curso'),
        ('user', '0008_alter_user_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='curso',
            field=models.ForeignKey(blank=True, default='------', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curso', to='srea.curso', verbose_name='Ciclo'),
        ),
    ]
