# Generated by Django 4.2.1 on 2023-06-28 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_indicacion_options_remove_indicacion_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
