# Generated by Django 4.1.4 on 2023-02-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ficha',
        ),
        migrations.RemoveField(
            model_name='user',
            name='indicacion',
        ),
        migrations.AddField(
            model_name='ficha',
            name='user',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userF', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicacion',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
