# Generated by Django 4.1.4 on 2023-01-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='indicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.indicacion', verbose_name='Indicación'),
        ),
    ]
