# Generated by Django 4.2.1 on 2023-07-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_ficha_ocupacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacion',
            name='documento',
            field=models.FileField(blank=True, null=True, upload_to='pdf/%Y/%m/%d', verbose_name='Subir documento'),
        ),
    ]
