# Generated by Django 4.2.1 on 2023-07-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_indicacion_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicacion',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
    ]
