# Generated by Django 4.2.1 on 2023-06-01 19:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('text', models.TextField()),
                ('state', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'db_table': 'answer',
                'ordering': ['question', 'text', 'createdAt', 'learning_style'],
            },
        ),
        migrations.CreateModel(
            name='FileUploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='archivo/%Y/%m/%d')),
                ('observation', models.CharField(max_length=200, null=True, verbose_name='Observation')),
            ],
            options={
                'verbose_name': 'file_uploaded',
                'verbose_name_plural': 'file_uploadeds',
                'db_table': 'file_uploaded',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('statement', models.TextField()),
                ('type_question', models.CharField(choices=[('T', 'Text'), ('S', 'Single'), ('M', 'Multiple')], default='S', max_length=1)),
                ('state', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
                'db_table': 'question',
                'ordering': ['quiz', 'statement', 'createdAt'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('time_limit', models.TimeField(default='01:00:00')),
                ('state', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'db_table': 'quiz',
                'ordering': ['name', 'createdAt', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('state', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='CreatedAt')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='UpdatedAt')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'user_response',
                'verbose_name_plural': 'user_responses',
                'db_table': 'user_response',
                'ordering': ['user', 'quiz', 'question', 'answer'],
            },
        ),
    ]
