# Generated by Django 4.1.4 on 2023-03-16 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='questions',
            field=models.ManyToManyField(to='quiz.question'),
        ),
        migrations.AddField(
            model_name='quizzes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_respuesta', to='quiz.respuesta'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='facultades',
            field=models.ManyToManyField(blank=True, related_name='facultades', to='quiz.facultad', verbose_name='Facultades'),
        ),
        migrations.AddField(
            model_name='cuestionario',
            name='pregunta',
            field=models.ManyToManyField(blank=True, related_name='preguntas', to='quiz.pregunta', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='attempter',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzes'),
        ),
        migrations.AddField(
            model_name='attempter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.answer'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.attempter'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='questions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzes'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
