# Generated by Django 4.1.4 on 2023-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0018_remove_respuesta_pregunta_and_more'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('asignaturas', models.ManyToManyField(blank=True, related_name='asignaturas', to='srea.asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='cuestionario',
            name='unidad',
            field=models.ManyToManyField(blank=True, related_name='unidades', to='quiz.unidad', verbose_name='Unidad'),
        ),
    ]
