# Generated by Django 4.1.4 on 2023-03-17 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='docente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='unidad_docente', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
            preserve_default=False,
        ),
    ]
