# Generated by Django 4.1.4 on 2023-03-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_unidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='cuestionario',
            field=models.ManyToManyField(blank=True, related_name='cuestionarios', to='quiz.quizzes', verbose_name='Cuestionario'),
        ),
    ]
