# Generated by Django 4.2.1 on 2023-06-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_quiz'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUploaded',
        ),
    ]
