# Generated by Django 4.1.4 on 2023-04-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_unidad_cuestionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answers',
        ),
    ]
