# Generated by Django 4.1.4 on 2023-04-03 19:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_quizzes_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='time_limit_mins',
            field=models.PositiveIntegerField(verbose_name='Tiempo limite'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
