# Generated by Django 4.1.4 on 2023-04-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_quizzes_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizzes',
            options={'verbose_name': 'Quizze', 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='time_limit_mins',
            field=models.PositiveIntegerField(verbose_name='Tiempo límite'),
        ),
    ]
