# Generated by Django 4.1.4 on 2023-04-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_quizzes_options_alter_quizzes_time_limit_mins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='questions',
            new_name='question',
        ),
    ]
