# Generated by Django 4.1.4 on 2023-04-10 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_questions_attempt_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizzes',
            name='user',
        ),
    ]
