# Generated by Django 4.1.4 on 2023-04-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_unidad_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='user',
        ),
    ]
