# Generated by Django 4.1.4 on 2023-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_question_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='quiz',
        ),
    ]
