# Generated by Django 4.1.4 on 2023-04-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_remove_answer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempter',
            name='user',
        ),
    ]
