# Generated by Django 4.1.4 on 2023-04-19 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_attempter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='question',
        ),
    ]
