# Generated by Django 4.1.4 on 2023-04-26 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_attempter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cat', models.CharField(max_length=900)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreItem', models.CharField(max_length=900)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoria')),
            ],
        ),
    ]
