# Generated by Django 4.1.4 on 2023-04-26 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0020_alter_categoria_options_alter_itemcat_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='categoria',
        ),
        migrations.AddField(
            model_name='question',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.categoria', verbose_name='Cat'),
            preserve_default=False,
        ),
    ]
