# Generated by Django 4.1.4 on 2023-04-26 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_remove_answer_categoria_question_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categoria',
        ),
        migrations.AddField(
            model_name='quizzes',
            name='cat',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quiz.categoria', verbose_name='Cat'),
            preserve_default=False,
        ),
    ]
