# Generated by Django 4.1.4 on 2023-04-27 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_remove_question_categoria_quizzes_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzes',
            name='allowed_attemps',
            field=models.PositiveIntegerField(verbose_name='Número de intentos'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='due',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
