# Generated by Django 4.1.4 on 2023-05-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_alter_quizzes_allowed_attemps_alter_quizzes_cat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='respuesta',
            field=models.SmallIntegerField(default=0),
        ),
    ]
