# Generated by Django 4.1.4 on 2023-05-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_remove_answer_is_correct_answer_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
    ]
