# Generated by Django 4.1.4 on 2023-03-16 19:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('duracion', models.PositiveSmallIntegerField(default=5, verbose_name='Duración')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultad', to='quiz.facultad', verbose_name='Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciclo', models.CharField(max_length=150, verbose_name='Nombre de ciclo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='srea.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('detalle', models.TextField(verbose_name='Detalle de la asignatura')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='asignatura/%Y/%m/%d')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo', to='srea.ciclo', verbose_name='Ciclo')),
                ('unidad', models.ManyToManyField(blank=True, related_name='unidad', to='quiz.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['id'],
            },
        ),
    ]
