# Generated by Django 4.2.1 on 2023-06-01 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='srea.carrera', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srea.catalog'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facultad', to='srea.facultad', verbose_name='Facultad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclo', to='srea.ciclo', verbose_name='Ciclo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_owner', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='unidad',
            field=models.ManyToManyField(blank=True, related_name='unidad', to='srea.unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
