# Generated by Django 4.1.4 on 2023-01-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='curso',
            name='asignatura',
            field=models.ManyToManyField(blank=True, null=True, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura'),
        ),
    ]
