# Generated by Django 4.1.4 on 2022-12-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('C', 'Cholo'), ('I', 'Indigena'), ('O', 'Otro'), ('A', 'Afroecuatoriano'), ('B', 'Blanco'), ('Me', 'Mestizo'), ('Mo', 'Montubio'), ('N', 'Negro'), ('Mu', 'Mulato')], max_length=10),
        ),
    ]
