# Generated by Django 4.1.4 on 2023-01-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipoPregunta',
            field=models.CharField(choices=[('om', 'opción multiple'), ('vf', 'Verdadero o Falso'), ('s', 'simple')], default=1, max_length=2, verbose_name='Tipo de preguntas'),
            preserve_default=False,
        ),
    ]
