# Generated by Django 4.0.6 on 2022-12-01 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichainformacion',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='imagen',
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('female', 'Femenino'), ('male', 'Masculino')], default='male', max_length=10, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('B', 'Blanco'), ('I', 'Indigena'), ('Mu', 'Mulato'), ('C', 'Cholo'), ('A', 'Afroecuatoriano'), ('O', 'Otro'), ('Mo', 'Montubio'), ('N', 'Negro'), ('Me', 'Mestizo')], max_length=10),
        ),
    ]
