# Generated by Django 4.0.6 on 2022-08-21 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('Mo', 'Montubio'), ('C', 'Cholo'), ('A', 'Afroecuatoriano'), ('N', 'Negro'), ('B', 'Blanco'), ('Mu', 'Mulato'), ('I', 'Indigena'), ('O', 'Otro')], max_length=2),
        ),
        migrations.CreateModel(
            name='Usuario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje total')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasRespondidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srea.pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='srea.respuesta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='srea.usuario2')),
            ],
        ),
    ]
