# Generated by Django 4.0.6 on 2022-10-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('B', 'Blanco'), ('Mo', 'Montubio'), ('N', 'Negro'), ('A', 'Afroecuatoriano'), ('I', 'Indigena'), ('O', 'Otro'), ('Mu', 'Mulato'), ('C', 'Cholo'), ('Me', 'Mestizo')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre'),
        ),
    ]
