# Generated by Django 4.1.4 on 2023-01-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_remove_curso_asignatura_curso_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='numero_ciclo',
        ),
        migrations.AddField(
            model_name='curso',
            name='nombre_ciclo',
            field=models.CharField(default=1, max_length=150, verbose_name='Nombre de ciclo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.ManyToManyField(blank=True, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura'),
        ),
    ]
