# Generated by Django 4.1.4 on 2023-01-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_pregunta_tipopregunta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='texto',
            new_name='pregunta',
        ),
    ]
