# Generated by Django 4.1.4 on 2022-12-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_remove_fichainformacion_genero_remove_usuario_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('I', 'Indigena'), ('N', 'Negro'), ('O', 'Otro'), ('B', 'Blanco'), ('A', 'Afroecuatoriano'), ('Me', 'Mestizo'), ('Mu', 'Mulato'), ('Mo', 'Montubio'), ('C', 'Cholo')], max_length=10),
        ),
    ]
