# Generated by Django 4.1.4 on 2023-03-17 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='docente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_owner', to=settings.AUTH_USER_MODEL, verbose_name='Docente'),
            preserve_default=False,
        ),
    ]
