# Generated by Django 4.1.4 on 2022-12-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('N', 'Negro'), ('B', 'Blanco'), ('O', 'Otro'), ('Mu', 'Mulato'), ('C', 'Cholo'), ('Me', 'Mestizo'), ('A', 'Afroecuatoriano'), ('I', 'Indigena'), ('Mo', 'Montubio')], max_length=10),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], default='Masculino', max_length=10, verbose_name='Genero'),
        ),
    ]
