# Generated by Django 4.2.1 on 2023-06-06 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_quiz'),
        ('srea', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_item', to='srea.catalog'),
        )
    ]
