# Generated by Django 4.0.6 on 2022-08-22 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_alter_fichainformacion_etnia_usuario2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntasrespondidas',
            old_name='usuario',
            new_name='quizUsuario',
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('N', 'Negro'), ('C', 'Cholo'), ('A', 'Afroecuatoriano'), ('B', 'Blanco'), ('I', 'Indigena'), ('Mu', 'Mulato'), ('Mo', 'Montubio'), ('O', 'Otro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='srea.pregunta'),
        ),
    ]
