# Generated by Django 4.0.6 on 2022-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0002_alter_fichainformacion_etnia_alter_usuario_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('Mo', 'Montubio'), ('A', 'Afroecuatoriano'), ('B', 'Blanco'), ('I', 'Indigena'), ('O', 'Otro'), ('Me', 'Mestizo'), ('C', 'Cholo'), ('N', 'Negro'), ('Mu', 'Mulato')], max_length=2),
        ),
    ]
