# Generated by Django 4.1.4 on 2022-12-26 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0003_alter_fichainformacion_etnia_alter_usuario_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('N', 'Negro'), ('O', 'Otro'), ('C', 'Cholo'), ('B', 'Blanco'), ('Me', 'Mestizo'), ('I', 'Indigena'), ('A', 'Afroecuatoriano'), ('Mu', 'Mulato'), ('Mo', 'Montubio')], max_length=10),
        ),
    ]
