# Generated by Django 4.1.4 on 2023-01-20 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0003_rename_texto_pregunta_pregunta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test', to='srea.test'),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pregunta_respuesta', to='srea.pregunta'),
        ),
    ]
