# Generated by Django 4.1.4 on 2023-01-31 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0003_remove_curso_numero_ciclo_curso_nombre_ciclo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='curso',
        ),
        migrations.AddField(
            model_name='carrera',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='curso', to='srea.curso', verbose_name='Curso'),
        ),
    ]
