# Generated by Django 4.0.6 on 2022-10-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0003_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('C', 'Cholo'), ('B', 'Blanco'), ('O', 'Otro'), ('Me', 'Mestizo'), ('N', 'Negro'), ('Mo', 'Montubio'), ('Mu', 'Mulato'), ('A', 'Afroecuatoriano'), ('I', 'Indigena')], max_length=2),
        ),
    ]
