# Generated by Django 4.0.6 on 2022-08-22 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0003_rename_usuario_preguntasrespondidas_quizusuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('Mo', 'Montubio'), ('C', 'Cholo'), ('N', 'Negro'), ('I', 'Indigena'), ('Mu', 'Mulato'), ('B', 'Blanco'), ('A', 'Afroecuatoriano'), ('O', 'Otro')], max_length=2),
        ),
        migrations.CreateModel(
            name='ElegirRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correcta', models.BooleanField(default=False, verbose_name='Respuesta correcta')),
                ('respuesta', models.TextField(verbose_name='Texto de la respuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='srea.pregunta')),
            ],
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='srea.elegirrespuesta'),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
