# Generated by Django 4.0.6 on 2022-10-19 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_remove_usuario_apellido_remove_usuario_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('C', 'Cholo'), ('N', 'Negro'), ('A', 'Afroecuatoriano'), ('Me', 'Mestizo'), ('Mo', 'Montubio'), ('Mu', 'Mulato'), ('B', 'Blanco'), ('O', 'Otro'), ('I', 'Indigena')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=True),
        ),
    ]
