# Generated by Django 4.1.4 on 2022-12-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_alter_asignatura_user_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('Mo', 'Montubio'), ('Mu', 'Mulato'), ('C', 'Cholo'), ('N', 'Negro'), ('I', 'Indigena'), ('B', 'Blanco'), ('A', 'Afroecuatoriano'), ('Me', 'Mestizo'), ('O', 'Otro')], max_length=10),
        ),
    ]
