# Generated by Django 4.1.4 on 2023-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_completion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='completion',
            old_name='course',
            new_name='asignatura',
        ),
    ]
