# Generated by Django 4.0.6 on 2022-08-30 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_alter_fichainformacion_etnia_elegirrespuesta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6, verbose_name='Máximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='elegirrespuesta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='srea.pregunta'),
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('I', 'Indigena'), ('C', 'Cholo'), ('Mo', 'Montubio'), ('N', 'Negro'), ('Mu', 'Mulato'), ('B', 'Blanco'), ('A', 'Afroecuatoriano'), ('O', 'Otro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='quizUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='srea.usuario2'),
        ),
    ]
