# Generated by Django 4.2.1 on 2023-06-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0004_remove_unidad_quizzes_unidad_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajenAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título del mensaje')),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripción del mensaje')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicación del mensaje')),
                ('asignatura', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['id'],
            },
        ),
    ]
