# Generated by Django 4.1.4 on 2023-01-31 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0004_remove_carrera_curso_carrera_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='facultad',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='facultad',
            name='carrera',
            field=models.ManyToManyField(blank=True, related_name='carrera', to='srea.carrera', verbose_name='Carrera'),
        ),
    ]
