# Generated by Django 4.0.6 on 2022-08-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0005_pregunta_max_puntaje_alter_elegirrespuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('I', 'Indigena'), ('C', 'Cholo'), ('O', 'Otro'), ('B', 'Blanco'), ('N', 'Negro'), ('Mo', 'Montubio'), ('A', 'Afroecuatoriano'), ('Mu', 'Mulato')], max_length=2),
        ),
    ]
