# Generated by Django 4.1.4 on 2022-12-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0005_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('A', 'Afroecuatoriano'), ('Mo', 'Montubio'), ('C', 'Cholo'), ('I', 'Indigena'), ('O', 'Otro'), ('Mu', 'Mulato'), ('Me', 'Mestizo'), ('N', 'Negro'), ('B', 'Blanco')], max_length=10),
        ),
    ]
