# Generated by Django 4.1.4 on 2023-01-24 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0005_alter_matricula_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
