# Generated by Django 4.2.1 on 2023-06-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0005_mensajenasignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajenasignatura',
            name='descripcion',
            field=models.TextField(blank=True, max_length=900, null=True, verbose_name='Descripción del mensaje'),
        ),
    ]
