# Generated by Django 4.1.4 on 2023-01-31 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0005_remove_carrera_facultad_asignatura_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='carrera',
            field=models.ManyToManyField(blank=True, related_name='carrera', to='srea.carrera', verbose_name='Carreras'),
        ),
    ]
