# Generated by Django 4.0.6 on 2022-10-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0005_alter_fichainformacion_etnia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_nacimiento',
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('N', 'Negro'), ('O', 'Otro'), ('A', 'Afroecuatoriano'), ('C', 'Cholo'), ('Me', 'Mestizo'), ('Mu', 'Mulato'), ('I', 'Indigena'), ('Mo', 'Montubio'), ('B', 'Blanco')], max_length=2),
        ),
    ]
