# Generated by Django 4.1.4 on 2023-01-24 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0006_alter_matricula_asignatura_alter_matricula_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='asignatura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura'),
        ),
    ]
