# Generated by Django 4.0.6 on 2022-08-30 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0006_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('B', 'Blanco'), ('C', 'Cholo'), ('Mu', 'Mulato'), ('N', 'Negro'), ('O', 'Otro'), ('A', 'Afroecuatoriano'), ('I', 'Indigena'), ('Mo', 'Montubio')], max_length=2),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='respuesta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='srea.elegirrespuesta'),
        ),
    ]
