# Generated by Django 4.1.4 on 2023-01-31 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0006_alter_facultad_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='user',
        ),
        migrations.AlterField(
            model_name='carrera',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='curso', to='srea.curso', verbose_name='Ciclos'),
        ),
    ]
