# Generated by Django 4.1.4 on 2023-04-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0006_alter_ciclo_nombre_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='nombre_ciclo',
            field=models.CharField(max_length=150, verbose_name='Nombre de ciclo'),
        ),
    ]
