# Generated by Django 4.0.6 on 2022-10-20 22:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0006_remove_usuario_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('C', 'Cholo'), ('N', 'Negro'), ('Me', 'Mestizo'), ('I', 'Indigena'), ('O', 'Otro'), ('Mu', 'Mulato'), ('A', 'Afroecuatoriano'), ('Mo', 'Montubio'), ('B', 'Blanco')], max_length=2),
        ),
    ]
