# Generated by Django 4.2.1 on 2023-06-20 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0007_alter_mensajenasignatura_asignatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajenasignatura',
            name='asignatura',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, related_name='asignatura', to='srea.asignatura', verbose_name='Asignatura'),
            preserve_default=False,
        ),
    ]
