# Generated by Django 4.1.4 on 2023-02-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0007_remove_asignatura_user_alter_carrera_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='curso',
            field=models.ManyToManyField(blank=True, related_name='ciclo', to='srea.curso', verbose_name='Ciclos'),
        ),
    ]
