# Generated by Django 4.0.6 on 2022-08-31 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0007_alter_fichainformacion_etnia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('O', 'Otro'), ('Mo', 'Montubio'), ('Mu', 'Mulato'), ('B', 'Blanco'), ('N', 'Negro'), ('I', 'Indigena'), ('A', 'Afroecuatoriano'), ('C', 'Cholo')], max_length=2),
        ),
    ]
