# Generated by Django 4.0.6 on 2022-10-20 22:09

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0007_alter_usuario_managers_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('object', django.db.models.manager.Manager()),
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('C', 'Cholo'), ('B', 'Blanco'), ('Mu', 'Mulato'), ('Me', 'Mestizo'), ('Mo', 'Montubio'), ('I', 'Indigena'), ('A', 'Afroecuatoriano'), ('N', 'Negro'), ('O', 'Otro')], max_length=2),
        ),
    ]
