# Generated by Django 4.2.1 on 2023-06-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0008_alter_mensajenasignatura_asignatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='docente',
        ),
    ]
