# Generated by Django 4.0.6 on 2022-10-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0008_alter_usuario_managers_alter_fichainformacion_etnia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichainformacion',
            name='etnia',
            field=models.CharField(choices=[('N', 'Negro'), ('Mo', 'Montubio'), ('O', 'Otro'), ('Me', 'Mestizo'), ('Mu', 'Mulato'), ('B', 'Blanco'), ('A', 'Afroecuatoriano'), ('C', 'Cholo'), ('I', 'Indigena')], max_length=2),
        ),
    ]
