# Generated by Django 4.1.4 on 2023-02-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0010_unidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unidad',
            old_name='asignatuturas',
            new_name='asignaturas',
        ),
    ]
