# Generated by Django 4.2.1 on 2023-06-26 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0010_fileuploaded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='quizzes',
        ),
    ]
