# Generated by Django 4.2.1 on 2023-06-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_fileuploaded'),
        ('srea', '0011_remove_unidad_quizzes'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_unidad', to='quiz.quiz', verbose_name='Registrar quiz')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidad_quiz', to='srea.unidad', verbose_name='Registrar unidad')),
            ],
        ),
    ]
