# Generated by Django 4.1.4 on 2023-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0011_rename_asignatuturas_unidad_asignaturas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='test',
            name='unidad',
            field=models.ManyToManyField(blank=True, related_name='unidad', to='srea.unidad', verbose_name='Unidad'),
        ),
    ]
