# Generated by Django 4.1.4 on 2023-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0012_remove_test_asignatura_test_unidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='tipoPregunta',
        ),
        migrations.AddField(
            model_name='test',
            name='numero_preguntas',
            field=models.IntegerField(default=1, verbose_name='Numero de preguntas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='tiempo',
            field=models.IntegerField(default=1, verbose_name='Duración del Test'),
            preserve_default=False,
        ),
    ]
