# Generated by Django 4.2.1 on 2023-06-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0012_unidadquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileuploaded',
            name='nombre',
            field=models.CharField(default=1, max_length=100, verbose_name='Nombre del archivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fileuploaded',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='archivo/%Y/%m/%d', verbose_name='Cargar archivo'),
        ),
        migrations.AlterField(
            model_name='fileuploaded',
            name='observation',
            field=models.CharField(max_length=200, null=True, verbose_name='Observación'),
        ),
    ]
