# Generated by Django 4.2.1 on 2023-06-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0013_fileuploaded_nombre_alter_fileuploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='unidad',
            field=models.ManyToManyField(blank=True, related_name='unidad_asignatura', to='srea.unidad', verbose_name='Unidad'),
        ),
    ]
