# Generated by Django 4.1.4 on 2023-02-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0013_remove_pregunta_tipopregunta_test_numero_preguntas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='correcta',
            field=models.BooleanField(default=False),
        ),
    ]
