# Generated by Django 4.2.1 on 2023-06-28 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0014_alter_asignatura_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
