# Generated by Django 4.2.1 on 2023-06-28 19:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0015_alter_unidad_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajenasignatura',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
