# Generated by Django 4.2.1 on 2023-06-28 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0016_alter_mensajenasignatura_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubirArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del archivo')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivo/%Y/%m/%d', verbose_name='Cargar archivo')),
                ('observación', models.CharField(max_length=200, null=True, verbose_name='Observación')),
            ],
            options={
                'verbose_name': 'subir_archivo',
                'verbose_name_plural': 'subir_archivos',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='fileuploaded',
            name='unid',
        ),
    ]
