# Generated by Django 4.1.4 on 2023-03-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0016_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='required_score_to_pass',
            field=models.IntegerField(default=1, verbose_name='Puntaje requerido'),
            preserve_default=False,
        ),
    ]
