# Generated by Django 4.1.4 on 2023-03-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0017_test_required_score_to_pass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respuesta',
            name='pregunta',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='cuestionario',
        ),
        migrations.RemoveField(
            model_name='resultado',
            name='user',
        ),
        migrations.RemoveField(
            model_name='test',
            name='unidad',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Resultado',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
