# Generated by Django 4.2.1 on 2023-06-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0017_subirarchivos_remove_fileuploaded_unid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subirarchivos',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='formato/%Y/%m/%d', verbose_name='Cargar archivo'),
        ),
    ]
