# Generated by Django 4.2.1 on 2023-06-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srea', '0018_alter_subirarchivos_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completion',
        ),
    ]
