# Generated by Django 4.1.4 on 2023-03-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_unidad_alter_cuestionario_unidad'),
        ('srea', '0018_remove_respuesta_pregunta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
