# Generated by Django 4.2.1 on 2023-06-30 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_delete_fileuploaded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srea', '0019_delete_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_users', to='quiz.quiz', verbose_name='Registrar quiz')),
                ('users', models.ManyToManyField(blank=True, related_name='users_quiz', to=settings.AUTH_USER_MODEL, verbose_name='Registrar usuario')),
            ],
        ),
    ]
